<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Troy Chaplin - Developer</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #0f0f23 0%, #1a1a3a 100%);
            color: #e0e0e0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }
        
        .container {
            text-align: center;
            max-width: 800px;
            padding: 2rem;
            position: relative;
            z-index: 2;
        }
        
        .background-animation {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 1;
        }
        
        .particle {
            position: absolute;
            background: rgba(59, 130, 246, 0.2);
            border-radius: 50%;
            pointer-events: none;
            will-change: transform, opacity;
        }
        
        .particle.yellow {
            background: rgba(251, 191, 36, 0.2);
        }
        
        @keyframes floatUp {
            0% { 
                transform: translateY(100vh) translateX(0px) rotate(0deg) scale(0);
                opacity: 0;
            }
            10% {
                opacity: 1;
                transform: translateY(90vh) translateX(0px) rotate(36deg) scale(1);
            }
            90% {
                opacity: 1;
                transform: translateY(10vh) translateX(var(--drift)) rotate(324deg) scale(1);
            }
            100% { 
                transform: translateY(-10vh) translateX(var(--drift)) rotate(360deg) scale(0);
                opacity: 0;
            }
        }
        
        @keyframes pulse {
            0%, 100% { opacity: 0.2; transform: scale(1); }
            50% { opacity: 0.4; transform: scale(1.1); }
        }
        
        h1 {
            font-size: 4rem;
            font-weight: 700;
            margin-bottom: 1.5rem;
            background: linear-gradient(135deg, #3b82f6, #fbbf24);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            text-shadow: 0 0 30px rgba(59, 130, 246, 0.3);
        }
        
        .subtitle {
            font-size: 1.5rem;
            color: #94a3b8;
            margin-bottom: 2rem;
            font-weight: 300;
        }
        
        .message {
            font-size: 1.25rem;
            line-height: 1.8;
            margin-bottom: 3rem;
            color: #cbd5e1;
        }
        
        .cta-button {
            display: inline-block;
            padding: 1rem 2.5rem;
            background: linear-gradient(135deg, #3b82f6, #2563eb);
            color: white;
            text-decoration: none;
            border-radius: 50px;
            font-size: 1.1rem;
            font-weight: 600;
            transition: all 0.3s ease;
            box-shadow: 0 10px 30px rgba(59, 130, 246, 0.3);
            position: relative;
            overflow: hidden;
        }
        
        .cta-button:hover {
            transform: translateY(-3px);
            box-shadow: 0 15px 40px rgba(59, 130, 246, 0.4);
            background: linear-gradient(135deg, #2563eb, #1d4ed8);
        }
        
        .cta-button::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
            transition: left 0.5s;
        }
        
        .cta-button:hover::before {
            left: 100%;
        }
        
        @media (max-width: 768px) {
            h1 {
                font-size: 2.5rem;
            }
            
            .subtitle {
                font-size: 1.2rem;
            }
            
            .message {
                font-size: 1.1rem;
            }
            
            .container {
                padding: 1rem;
            }
        }
    </style>
</head>
<body>
    <div class="background-animation">
        <!-- Animated particles will be generated by JavaScript -->
    </div>
    
    <div class="container">
        <h1>Troy Chaplin</h1>
        <div class="subtitle">Senior Frontend Engineer</div>
        <div class="message">
            Site is currently being moved to a new location.<br>
            In the meantime, check out my work and projects below.
        </div>
        <a href="https://github.com/troychaplin" class="cta-button" target="_blank">
            Visit GitHub Profile →
        </a>
    </div>
    
    <script>
        // Improved particle system with smoother animations
        const particleContainer = document.querySelector('.background-animation');
        const maxParticles = 15;
        let particles = [];
        
        function createSmoothParticle() {
            if (particles.length >= maxParticles) return;
            
            const particle = document.createElement('div');
            particle.className = Math.random() > 0.5 ? 'particle' : 'particle yellow';
            
            const size = Math.random() * 3 + 1;
            const startX = Math.random() * window.innerWidth;
            const driftX = (Math.random() - 0.5) * 200; // Horizontal drift
            const duration = Math.random() * 8 + 12; // 12-20 seconds
            const delay = Math.random() * 5;
            
            particle.style.width = size + 'px';
            particle.style.height = size + 'px';
            particle.style.left = startX + 'px';
            particle.style.setProperty('--drift', driftX + 'px');
            particle.style.animation = `floatUp ${duration}s linear ${delay}s forwards, pulse 3s ease-in-out infinite`;
            
            particleContainer.appendChild(particle);
            particles.push(particle);
            
            // Remove particle after animation completes
            setTimeout(() => {
                if (particle.parentNode) {
                    particle.remove();
                    particles = particles.filter(p => p !== particle);
                }
            }, (duration + delay) * 1000);
        }
        
        // Create initial particles with staggered timing
        for (let i = 0; i < maxParticles; i++) {
            setTimeout(() => createSmoothParticle(), i * 800);
        }
        
        // Continuously create new particles
        setInterval(() => {
            if (particles.length < maxParticles) {
                createSmoothParticle();
            }
        }, 1500);
    </script>
</body>
</html>
